# Define the name of the ESPHome project
esphome:
  name: esphome-growatt
  friendly_name: Growatt

# Define the exact board being used
esp8266:
  board: esp01_1m

# Disable hardware serial logging as it conflicts with the serial connection
# with the MAX485 TTL converter module by setting baud rate to zero
logger:
  baud_rate: 0
  
# Enable Home Assistant API
api:
  encryption:
    key: "=heregoestheapikey="

# Enable over the air updates (ota)
ota:
  - platform: esphome
  
# Define how the device connects to Wifi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esphome-growatt"
    password: "SSw2Oy8kDY3r"

# Define a captive portal as fallback in case connecting ti Wifi fails
captive_portal:
    
# Define the UART communication settings
# GPIO1 and GPIO3 are the hardware supported serial TX and RX pins
uart:
  - id: gw_uart
    baud_rate: 9600
    tx_pin: GPIO1
    rx_pin: GPIO3

# Define the modbus specific settings
modbus:
  uart_id: gw_uart
  flow_control_pin: GPIO4

# Define the protocol version and the sensors for this device.
# Old inverters use RTU (default). Newer ones use RTU2 (e.g. MIC, MIN, MAX series)
sensor:
  - platform: growatt_solar
    update_interval: 10s
    protocol_version: RTU2

    inverter_status:
      name: "Status Code"

    phase_a:
      voltage:
          name: "Voltage Phase A"
      current:
          name: "Current Phase A"
      active_power:
          name: "Power Phase A"
    phase_b:
      voltage:
          name: "Voltage Phase B"
      current:
          name: "Current Phase B"
      active_power:
          name: "Power Phase B"
    phase_c:
      voltage:
          name: "Voltage Phase C"
      current:
          name: "Current Phase C"
      active_power:
          name: "Power Phase C"

    pv1:
      voltage:
          name: "PV1 Voltage"
      current:
          name: "PV1 Current"
      active_power:
          name: "PV1 Active Power"

    pv2:
      voltage:
          name: "PV2 Voltage"
      current:
          name: "PV2 Current"
      active_power:
          name: "PV2 Active Power"

    active_power:
      name: "Grid Active Power"

    pv_active_power:
      name: "PV Active Power"

    frequency:
      name: "Frequency"

    energy_production_day:
      name: "Today's Generation"

    total_energy_production:
      name: "Total Energy Production"

    inverter_module_temp:
      name: "Inverter Module Temp"
